title: Jesstern

theme: PaperMod
languageCode: en-us
baseURL: "https://jsstrn.me/"

paginate: 10
enableGitInfo: true

taxonomies:
  category: categories
  tag: tags

menu:
  main:
    - name: Notes
      url: notes/
      weight: 1
    - name: About
      url: about/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - name: Search
      url: search/
      weight: 99

params:
  author: "Jesstern Rays"
  defaultTheme: auto

  ShowToc: false
  TocOpen: false

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "Hello, I'm Jesstern! 👋"
    subtitle: "Welcome to my personal digital space."
    imageUrl: "https://avatars.githubusercontent.com/u/1199611?v=4"
    imageWidth: 150
    imageHeight: 150
    imageTitle: "Jesstern Rays"

  homeInfoParams:
    Title: "Hello, I'm Jesstern! 👋"
    Content: "Welcome to my personal digital space."

  socialIcons:
    - name: "LinkedIn"
      url: "https://linkedin.com/in/jesstern"
    - name: "GitHub"
      url: "https://github.com/jsstrn"
    - name: "Email"
      url: "hello@jsstrn.me"

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/safari-pinned-tab.svg"

outputs:
  home:
    - HTML
    - RSS
    - JSON
